package io.github.varunscyther.drools

import io.github.varunscyther.drools.facts.Person;
import io.github.varunscyther.drools.facts.Address;

rule "Rule with nested None"
dialect "java"
when
    (
    not(
        (
            a : Person(  )  and
            b : Person( firstName == "VARUN", lastName == "SINGH" ) and
            c : Address(houseNumber == "77", streetName == "BELL COURT") from b.getSubModelAddressList()
        )
        )
    )
then
    System.out.println( "Rule Matched..." );
end